Migration from Swift 2.3 to Swift 3.0
tatey/LIFXHTTPKit pull request #10
Opened 2017-04-06 08:21 UTC by mitulmanish

2017-04-07 02:45 UTC, tatey commented
Thank you! I will try to review shortly. Initial impression is :+1:

2017-05-17 10:33 UTC, tatey requested changes
Hey @mitulmanish. Thanks a tonne for making this PR. I like the addition of `ProductInformation` and all the Swift 3 goodness.

Before merging there's a couple of things I'd like help with:

* Curious to understand more about making the handler properties on `ClientObserver` and `LightObserver` optional.
* There's a tonne of additional whitespace that's resulting in a lot more changes than needed. Would you mind cleaning this up?

Otherwise I'd love to merge this in. Please feel free to ask me anything. I'm also happy to help.

2017-05-17 10:33 UTC, tatey commented on Source/Client.swift
> +
Please delete this extra whitespace. I know Xcode sucks at adding whitespace, but I try to catch it in diffs.

2017-05-17 10:33 UTC, tatey commented on Source/ClientObserver.swift
> +	let lightsDidUpdateHandler: LightsDidUpdate?
What's the motivation for making this property optional? The original intent behind this class was to let you bind observers to listen for changes to the client. If you intend to have a nil callback, why not just skip setting up an observer?

Would you be able to share a use case?

2017-05-17 10:33 UTC, tatey commented on Source/Light.swift
> +	public let productInformation: ProductInformation?
I would have preferred to see this called `productInfo` since that would feel closer to Cocoa (Eg: `userInfo`).

2017-05-17 13:31 UTC, mitulmanish commented
@tatey Thanks for the detailed feedback.I have made the necessary changes.The changes currently live on https://github.com/LIFX/LIFXHTTPKit/pull/3.I will be testing this branch locally and if all is good I will push the changes upstream.

2017-05-18 10:43 UTC, tatey commented
Great. Look forward to it.

2017-06-12 11:06 UTC, tatey approved these changes

2017-06-12 11:06 UTC, tatey commented
Thanks a tonne for the patch.

2017-06-12 11:06 UTC, merged

2017-06-12 11:33 UTC, tatey commented
I've pushed out a new release https://github.com/tatey/LIFXHTTPKit/releases/tag/3.0.0.